#!/usr/bin/env python3
"""Compile the real IR receiver sources against a small simulated host device."""

from pathlib import Path
import subprocess
import sys
import tempfile

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from ir_upload_v2 import image_frames, CMD_START, CMD_DATA, CMD_END, CMD_PARITY


TEST_DIR = Path(__file__).resolve().parent
STUB_HEADERS = (
    "system.h",
    "irq.h",
    "generated/mem.h",
    "generated/csr.h",
    "generated/soc.h",
    "sfl.h",
    "pogobot.h",
    "pogobot_ir.h",
    "libbase/crc.h",
    "libbase/spiflash.h",
)


def main():
    with tempfile.TemporaryDirectory(prefix="pogobot-ir-test-") as temp:
        temp_dir = Path(temp)
        # The C harness supplies hardware symbols; empty headers keep the
        # production source unchanged while excluding target-only headers.
        for name in STUB_HEADERS:
            header = temp_dir / name
            header.parent.mkdir(parents=True, exist_ok=True)
            header.write_text("#pragma once\n")

        executable = temp_dir / "ir_upload_fault_test"
        # Feed actual Python uploader payloads through the C receiver harness.
        image = bytes((i // 64 * 17 + i % 64 * 3 + 1) & 0xff for i in range(65))
        frames = list(image_frames(image, 0x260000, 0x12345678))
        assert [command for command, _ in frames] == [CMD_START, CMD_DATA, CMD_DATA, CMD_END]
        assert len(frames[2][1]) == 7  # ID, index, and one-byte final chunk.
        for invalid_image, invalid_address in ((b"", 0x260000),
                                               (image, 0x220000),
                                               (bytes(0x20001), 0x260000)):
            try:
                list(image_frames(invalid_image, invalid_address, 1))
            except ValueError:
                pass
            else:
                raise AssertionError("uploader accepted an invalid image or destination")
        fixture = temp_dir / "python_wire_fixture.bin"
        with fixture.open("wb") as output:
            for command, payload in frames:
                output.write(command + bytes([len(payload)]) + payload)

        # Exercise the production decoder with parity generated by the PC
        # uploader, including a short final chunk and an unrecoverable group.
        fec_length = 17 * 64 + 1
        fec_image = bytes((i // 64 * 17 + i % 64 * 3 + 1) & 0xff
                          for i in range(fec_length))
        fec_frames = list(image_frames(fec_image, 0x260000, 0x76543210, fec=True))
        cases = (
            ({0, 4, 9, 15}, set(), False),
            ({1, 7, 12}, {2}, False),
            ({0, 4, 9, 15}, {2}, False),
            ({17}, set(), False),
            ({0}, set(), True),
        )
        fec_fixtures = []
        for case_index, (missing_data, missing_parity, corrupt_parity) in enumerate(cases):
            path = temp_dir / f"python_fec_{case_index}.bin"
            with path.open("wb") as output:
                for command, payload in fec_frames:
                    if command == CMD_DATA and int.from_bytes(payload[4:6], "big") in missing_data:
                        continue
                    if command == CMD_PARITY and payload[4:6] == b"\x00\x00" and \
                            payload[6] in missing_parity:
                        continue
                    if corrupt_parity and command == CMD_PARITY and \
                            payload[4:7] == b"\x00\x00\x00":
                        modified = bytearray(payload)
                        modified[7] ^= 1
                        payload = bytes(modified)
                    output.write(command + bytes([len(payload)]) + payload)
            fec_fixtures.append(path)

        repeated_fixture = temp_dir / "python_fec_repeated.bin"
        with repeated_fixture.open("wb") as output:
            for pass_number in range(2):
                for command, payload in fec_frames:
                    if command == CMD_DATA:
                        index = int.from_bytes(payload[4:6], "big")
                        if pass_number == 0 and index in {0, 4, 7, 9, 15}:
                            continue
                        if pass_number == 1 and index != 0:
                            continue
                    if pass_number == 1 and command == CMD_PARITY and \
                            payload[4:6] != b"\x00\x00":
                        continue
                    output.write(command + bytes([len(payload)]) + payload)

        # A 64 KiB fixture cycles through every Cauchy coefficient: each of
        # 64 groups loses one data symbol and retains one distinct parity row.
        large_length = 64 * 16 * 64
        large_image = bytes((i // 64 * 17 + i % 64 * 3 + 1) & 0xff
                            for i in range(large_length))
        large_fixture = temp_dir / "python_fec_64k.bin"
        with large_fixture.open("wb") as output:
            for command, payload in image_frames(large_image, 0x260000,
                                                 0x0fec6410, fec=True):
                if command == CMD_DATA:
                    index = int.from_bytes(payload[4:6], "big")
                    if index % 16 == (index // 16) % 16:
                        continue
                if command == CMD_PARITY:
                    group = int.from_bytes(payload[4:6], "big")
                    if payload[6] != group // 16:
                        continue
                output.write(command + bytes([len(payload)]) + payload)
        subprocess.run(
            [
                "cc", "-std=c11", "-O1", "-g", "-Wall", "-Wextra",
                "-fsanitize=address,undefined", "-fno-omit-frame-pointer",
                "-I", str(temp_dir),
                "-I", str(TEST_DIR.parent / "pogobios"),
                "-I", str(TEST_DIR.parent / "pogolib"),
                str(TEST_DIR / "ir_upload_fault_test.c"),
                "-o", str(executable),
            ],
            check=True,
        )
        subprocess.run([str(executable), str(fixture),
                        *(str(path) for path in fec_fixtures),
                        str(large_fixture), str(repeated_fixture)], check=True)


if __name__ == "__main__":
    main()
